name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.Commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: cd example    
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd example/build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email sensn.sound@gmail.com
          git config --global user.name sensn
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/particle_field.git then the following:
          git remote add origin https://${{secrets.Commit_secret}}@github.com/sensn/particle_field.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f   
